name: Fetch calair_tiemporeal (daily)

on:
  # Arranca a las 23:00 Madrid y repite cada 15 min hasta ~01:45
  # Notas de huso horario: definimos dos ventanas (verano/invierno) en UTC
  - cron: "0,15,30,45 21,22,23 * * *"   # 23:00→01:45 Madrid en verano (UTC+2)
  - cron: "0,15,30,45 22,23,0 * * *"    # 23:00→01:45 Madrid en invierno (UTC+1)
  workflow_dispatch:
    inputs:
      max_retries:
        description: "CALAIR_MAX_RETRIES (default 2)"
        required: false
        default: "2"
      wait_seconds:
        description: "CALAIR_WAIT_SECONDS (default 180)"
        required: false
        default: "180"

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Show HEAD and script version
        run: |
          git log -1 --oneline
          echo "==== scripts/fetch_calair.py (primeras 60 líneas) ===="
          sed -n '1,60p' scripts/fetch_calair.py || true

      - name: Quick API sanity (curl)
        run: |
          set -e
          echo "HEADERS >>>"
          curl -I --retry 3 --max-time 30 "https://ciudadesabiertas.madrid.es/dynamicAPI/API/query/calair_tiemporeal.json?pageSize=5000" || true
          echo "SAMPLE (first 500 bytes) >>>"
          curl -s --retry 3 --max-time 60 "https://ciudadesabiertas.madrid.es/dynamicAPI/API/query/calair_tiemporeal.json?pageSize=5000" | head -c 500 || true
          echo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run fetch script (JSON + CSV + history.csv)
        run: |
          set -e
          # Reintentos y espera configurables (inputs -> env)
          export CALAIR_MAX_RETRIES="${{ github.event.inputs.max_retries || '2' }}"
          export CALAIR_WAIT_SECONDS="${{ github.event.inputs.wait_seconds || '180' }}"
          python scripts/fetch_calair.py

      - name: List output files
        run: |
          echo "=== Tree data/calair ==="
          ls -Ral data/calair || true
          echo "=== history.csv head/tail ==="
          head -n 3 data/calair/history.csv || true
          tail -n 3 data/calair/history.csv || true

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add data/calair
            git commit -m "chore: daily calair (json+csv) + update history.csv [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
