name: Fetch Decide Madrid proposals (latest)

on:
  schedule:
    # Dos disparos y compuerta para asegurar 23:59 Europe/Madrid todo el año
    - cron: '59 21 * * *'
    - cron: '59 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      DECIDE_MADRID_URL: ${{ vars.DECIDE_MADRID_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gate at 23:59 Europe/Madrid
        id: gate
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          set -euo pipefail
          if [ "${EVENT_NAME}" = "workflow_dispatch" ]; then
            echo "Manual run detected; bypassing time gate"
            echo "run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          now=$(TZ=Europe/Madrid date +'%H:%M')
          echo "Local time (Europe/Madrid): $now"
          if [ "$now" = "23:59" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Fetch and filter CSV (inline)
        id: fetch
        if: steps.gate.outputs.run == 'true'
        run: |
          set -euo pipefail
          mkdir -p decide-madrid
          url="${DECIDE_MADRID_URL:-https://decide.madrid.es/system/api/proposals.csv}"
          echo "Fetching: $url"
          tmp=$(mktemp)
          hdrs=$(mktemp)
          cookies=$(mktemp)

          origin=$(echo "$url" | sed -E 's#(https?://[^/]+).*#\1/#')
          curl -sSL --fail --compressed --http1.1 \
            --retry 2 --retry-delay 2 \
            -c "$cookies" -b "$cookies" \
            -D /dev/null \
            -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
            -H "Accept-Language: es-ES,es;q=0.9,en;q=0.8" \
            -H "Connection: keep-alive" \
            -H "Referer: $origin" \
            "$origin" || true

          curl -sSL --fail --compressed --http1.1 \
            --retry 3 --retry-delay 2 --retry-all-errors \
            -c "$cookies" -b "$cookies" \
            -D "$hdrs" -o "$tmp" \
            -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" \
            -H "Accept: text/csv, text/plain;q=0.9, */*;q=0.1" \
            -H "Accept-Language: es-ES,es;q=0.9,en;q=0.8" \
            -H "Connection: keep-alive" \
            -H "Sec-Fetch-Site: same-origin" \
            -H "Sec-Fetch-Mode: navigate" \
            -H "Sec-Fetch-Dest: document" \
            -H "Upgrade-Insecure-Requests: 1" \
            -H "Referer: $origin" \
            "$url"

          if [ ! -s "$tmp" ]; then
            echo "Downloaded file is empty" >&2
            exit 1
          fi
          ctype=$(grep -i '^content-type:' "$hdrs" | tail -1 | tr -d '\r' | awk -F': ' '{print tolower($2)}') || true
          if [ -n "$ctype" ] && ! echo "$ctype" | grep -Eq 'text/csv|application/csv|text/plain'; then
            echo "Unexpected content-type: $ctype" >&2
            exit 1
          fi
          if head -c 20 "$tmp" | grep -qi '<html'; then
            echo "Server returned HTML (likely 403)" >&2
            exit 1
          fi

          # Normalize to app schema and optionally filter by date
          filt=$(mktemp)
          python3 scripts/decide_madrid_filter.py \
            --in "$tmp" \
            --out "$filt" \
            --from-date 2024-01-01 \
            --normalize

          dest="decide-madrid/proposals_latest.csv"
          if [ -f "$dest" ] && cmp -s "$filt" "$dest"; then
            echo "No changes after filtering"
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            mv "$filt" "$dest"
            echo "Updated $dest"
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate summary metrics
        if: steps.gate.outputs.run == 'true' && steps.fetch.outputs.no_changes == 'false'
        run: |
          set -euo pipefail
          python3 scripts/decide_madrid_summary.py \
            --in decide-madrid/proposals_latest.csv \
            --compare-git \
            --out-json decide-madrid/proposals_summary.json \
            --out-md decide-madrid/proposals_summary.md

      - name: Publish summary to job summary
        if: steps.gate.outputs.run == 'true' && steps.fetch.outputs.no_changes == 'false'
        run: |
          set -euo pipefail
          if [ -f decide-madrid/proposals_summary.md ]; then
            echo "\n## Summary (from script)\n" >> "$GITHUB_STEP_SUMMARY"
            cat decide-madrid/proposals_summary.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No hay resumen para publicar (posible ausencia de cambios)" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Commit and push if changed
        if: steps.gate.outputs.run == 'true' && steps.fetch.outputs.no_changes == 'false'
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add decide-madrid/proposals_latest.csv
          git add decide-madrid/proposals_summary.json decide-madrid/proposals_summary.md || true
          git commit -m "chore(decide-madrid): update proposals (normalized for app schema)"
          git push
