name: Fetch Decide Madrid proposals (latest)

on:
  schedule:
    # Dos disparos y compuerta para asegurar 23:59 Europe/Madrid todo el año
    - cron: '59 21 * * *'
    - cron: '59 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gate at 23:59 Europe/Madrid
        id: gate
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          set -euo pipefail
          if [ "${EVENT_NAME}" = "workflow_dispatch" ]; then
            echo "Manual run detected; bypassing time gate"
            echo "run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          now=$(TZ=Europe/Madrid date +'%H:%M')
          echo "Local time (Europe/Madrid): $now"
          if [ "$now" = "23:59" ]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node.js
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build TypeScript tools
        if: steps.gate.outputs.run == 'true'
        run: |
          set -euo pipefail
          npm install --no-save typescript
          npx tsc

      - name: Run fetch script (TS)
        id: fetch
        if: steps.gate.outputs.run == 'true'
        run: |
          set -euo pipefail
          node scripts/dist/fetch_decide_proposals.js

      - name: Publish summary to job summary
        if: steps.gate.outputs.run == 'true'
        run: |
          set -euo pipefail
          if [ -f decide-madrid/proposals_summary.md ]; then
            echo "\n## Summary (from script)\n" >> "$GITHUB_STEP_SUMMARY"
            cat decide-madrid/proposals_summary.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No hay resumen para publicar (posible ausencia de cambios)" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Push (if a commit was created)
        if: steps.gate.outputs.run == 'true'
        run: |
          set -e
          git push origin HEAD:main || true
