name: Fetch calair_tiemporeal (daily)

on:
  schedule:
    - cron: "59 21 * * *"   # 23:59 Madrid en verano (UTC+2)
    - cron: "59 22 * * *"   # 23:59 Madrid en invierno (UTC+1)
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Show HEAD and script version
        run: |
          git log -1 --oneline
          echo "==== scripts/fetch_calair.py (primeras 60 líneas) ===="
          sed -n '1,60p' scripts/fetch_calair.py || true

      - name: Quick API sanity (curl)
        run: |
          set -e
          echo "HEADERS >>>"
          curl -I --retry 3 --max-time 30 "https://ciudadesabiertas.madrid.es/dynamicAPI/API/query/calair_tiemporeal.json?pageSize=5000" || true
          echo "SAMPLE (first 500 bytes) >>>"
          curl -s --retry 3 --max-time 60 "https://ciudadesabiertas.madrid.es/dynamicAPI/API/query/calair_tiemporeal.json?pageSize=5000" | head -c 500 || true
          echo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run fetch script (JSON + CSV + history.csv)
        run: |
          set -e
          python scripts/fetch_calair.py

      - name: List output files
        run: |
          echo "=== Tree data/calair ==="
          ls -Ral data/calair || true
          echo "=== history.csv head/tail ==="
          head -n 3 data/calair/history.csv || true
          tail -n 3 data/calair/history.csv || true

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add data/calair
            git commit -m "chore: daily calair (json+csv) + update history.csv [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
