name: Fetch Madrid Air Quality (yesterday)

on:
  schedule:
    - cron: "15 7 * * *"  # 07:15 UTC ≈ 09:15 CEST
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Compute yesterday in Europe/Madrid
        id: date
        run: |
          python3 - <<'PY' >> "$GITHUB_OUTPUT"
          from datetime import datetime, timedelta
          from zoneinfo import ZoneInfo
          y = (datetime.now(ZoneInfo("Europe/Madrid")) - timedelta(days=1))
          print(f"YEAR={y:%Y}")
          print(f"MONTH={y:%m}")
          print(f"DAY={y:%d}")
          PY

      - name: Fetch dataset with retry
        run: |
          set -euo pipefail
          YEAR='${{ steps.date.outputs.YEAR }}'
          MONTH='${{ steps.date.outputs.MONTH }}'
          DAY='${{ steps.date.outputs.DAY }}'
          URL="https://datos.madrid.es/egob/catalogo/300755-12751602-calidad-aire-tiempo-real-acumula.json?MES=${MONTH}&ANO=${YEAR}&DIA=${DAY}"
          echo "Fetching: $URL"

          sudo apt-get update -y >/dev/null
          sudo apt-get install -y jq >/dev/null

          for attempt in 1 2 3 4 5 6; do
            code=$(curl -sS -w '%{http_code}' -L -o calair.json "$URL" || echo 000)
            if [ "$code" = "200" ] && [ -s calair.json ] && jq -e . calair.json >/dev/null 2>&1; then
              echo "OK on attempt $attempt"
              break
            fi
            echo "Not ready (code=$code). Retrying in 10 minutes..."
            sleep 600
          done

          if ! [ -s calair.json ]; then
            echo "Data not available yet, failing job so it retries later." >&2
            exit 1
          fi

      - name: Save file
        run: |
          set -euo pipefail
          YEAR='${{ steps.date.outputs.YEAR }}'
          MONTH='${{ steps.date.outputs.MONTH }}'
          DAY='${{ steps.date.outputs.DAY }}'
          mkdir -p datasets/calidad-aire/"$YEAR"/"$MONTH"
          mv calair.json datasets/calidad-aire/"$YEAR"/"$MONTH"/"$DAY".json
          echo "Saved to datasets/calidad-aire/$YEAR/$MONTH/$DAY.json"

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "calidad-aire: fetch ${{ steps.date.outputs.YEAR }}-${{ steps.date.outputs.MONTH }}-${{ steps.date.outputs.DAY }} (Europe/Madrid yesterday)"
          file_pattern: datasets/calidad-aire/**

