name: Update Tangible Climate Calendar CSV

on:
  schedule:
    - cron: '0 * * * *'  # hourly
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tangible-climate-calendar/requirements.txt

      - name: Fetch ICS and write CSV
        env:
          ICS_URL: ${{ secrets.HELLO_CAL_ICS_URL }}
        run: |
          python tangible-climate-calendar/fetch_calendar.py

      - name: Commit and push changes (if any)
        run: |
          set -e
          if [[ -n "$(git status --porcelain tangible-climate-calendar/calendar.csv)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add tangible-climate-calendar/calendar.csv
            git commit -m "chore(calendar): update tangible climate calendar CSV"
            git push
          else
            echo "No changes to commit."
          fi
